import 'dart:convert';

import 'package:equatable/equatable.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore: must_be_immutable
class HabitRecords extends Equatable {
  int time;
  String content;

  HabitRecords({
    this.time,
    this.content,
  });

  @override
  String toString() {
    return 'HabitRecords{time: $time, content: $content}';
  }

  HabitRecords.fromJson(Map<String, dynamic> json) {
    time = json["time"]?.toInt();
    content = json["content"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["time"] = time;
    data["content"] = content;
    return data;
  }

  @override
  // TODO: implement props
  List<Object> get props => [time, content];
}

// ignore: must_be_immutable
class Habit extends Equatable {
  ///唯一id uuid v4
  String id;
  String name;
  String iconPath;
  int mainColor;
  String mark;

  ///提醒时间 每天 10: 20，eg
  ///转化为 json String 存储 ["10:20","11:50"]
  List<String> remindTimes;

  ///完成时间
  /// 0 任意 1 早上 2 上午 3 中午 4 下午 5 晚上
  int completeTime;

  ///按周时 完成的day
  /// 1-7，周一 -- 周日
  List<int> completeDays;

  ///周期
  /// 0 按天
  /// 1 按周
  /// 2 按月
  int period;

  ///创建时间
  int createTime;

  ///修改时间
  int modifyTime;

  ///是否完成
  bool completed;

  ///次数
  int doNum;

  ///日志
  ///转化为 json String 存储
  List<HabitRecords> records;

  ///当天打卡时间记录
  List<int> todayChek;

  ///所有打卡记录
  Map<String, List<int>> totalCheck;

  Habit(
      {this.id,
      this.name,
      this.iconPath,
      this.mainColor,
      this.mark,
      this.remindTimes,
      this.completeDays,
      this.completeTime,
      this.period,
      this.createTime,
      this.modifyTime,
      this.completed,
      this.doNum,
      this.records,
      this.todayChek,
      this.totalCheck});

  @override
  String toString() {
    return 'Habit{id: $id, name: $name, iconPath: $iconPath, mainColor: $mainColor, mark: $mark,'
        ' remindTimes: $remindTimes, completeTime: $completeTime, completeDays:$completeDays, period: $period, '
        'createTime: $createTime, modifyTime: $modifyTime, completed: $completed, doNum: $doNum, records: $records'
        'todayCheck: $todayChek, totalCheck: $totalCheck}';
  }

  Habit.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    iconPath = json["iconPath"]?.toString();
    mainColor = json["mainColor"]?.toInt();
    mark = json["mark"]?.toString();
    if (json["remindTimes"] != null) {
      var timesJson = jsonDecode(json["remindTimes"]);
      var times = List<String>();
      timesJson.forEach((json) {
        times.add(json.toString());
      });
      remindTimes = times;
    }
    if (json["completeDays"] != null) {
      var daysJson = jsonDecode(json["completeDays"]);
      var days = List<int>();
      daysJson.forEach((json) {
        days.add(json.toInt());
      });
      completeDays = days;
    }
    completeTime = json['completeTime']?.toInt();
    period = json["period"]?.toInt();
    createTime = json["createTime"]?.toInt();
    modifyTime = json["modifyTime"]?.toInt();
    completed = json["completed"]?.toInt() == 1 ? true : false;
    doNum = json["doNum"]?.toInt();
    //String 先转化为Json，这是从数据库中取出来的字符串
    if (json["records"] != null) {
      var recordsJson = jsonDecode(json["records"]);
      var recordList = List<HabitRecords>();
      recordsJson.forEach((json) {
        recordList.add(HabitRecords.fromJson(json));
      });
      records = recordList;
    }

    if (json['todayCheck'] != null) {
      var checkJson = jsonDecode(json['todayCheck']) as List;
      var checks = List<int>();
      checkJson.forEach((json) {
        checks.add(json.toInt());
      });
      todayChek = checks;
    }

    if (json['totalCheck'] != null) {
      var checkJson = jsonDecode(json['totalCheck']) as List;
      var checks = Map<String, List<int>>();
      checkJson.forEach((json) {
        String value = json as String;
        List<String> values = value.split(':');
        print(values[0]);
        List<int> time = List();
        var times = jsonDecode(values[1]) as List;
        times.forEach((element) {
          time.add(element.toInt());
        });
        checks[values[0]] = time;
      });
      totalCheck = checks;
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["iconPath"] = iconPath;
    data["mainColor"] = mainColor;
    data["mark"] = mark;
    //转化为String 存储
    if (remindTimes != null) {
      var times = remindTimes;
      var temp = List();
      times.forEach((time) {
        temp.add(time);
      });
      data["remindTimes"] = jsonEncode(temp);
    }
    if (completeDays != null) {
      var days = completeDays;
      var temp = List();
      days.forEach((day) {
        temp.add(day);
      });
      data["completeDays"] = jsonEncode(temp);
    }

    data['completeTime'] = completeTime;
    data["period"] = period;
    data["createTime"] = createTime;
    data["modifyTime"] = modifyTime;
    data["completed"] = completed ? 1 : 0;
    data["doNum"] = doNum;
    //转化为String 存储
    if (records != null) {
      var recordList = records;
      var temp = List();
      recordList.forEach((record) {
        temp.add(record.toJson());
      });
      data["records"] = jsonEncode(temp);
    }
    if (todayChek != null) {
      var checks = todayChek;
      var temp = List();
      checks.forEach((check) {
        temp.add(check);
      });
      data["todayCheck"] = jsonEncode(temp);
    }
    if (totalCheck != null) {
      var checks = totalCheck;
      var temp = List();
      checks.forEach((key, value) {
        temp.add('$key:${jsonEncode(value)}');
      });
      data['totalCheck'] = jsonEncode(temp);
    }
    return data;
  }

  static Habit createHabit(String key) {
    return Habit(
        id: 'id__$key',
        name: 'name__$key',
        iconPath: 'assets/images/tab_1.png',
        mainColor: 122,
        mark: 'mark__$key',
        remindTimes: ['time1', 'time2'],
        period: 1,
        createTime: 1111,
        modifyTime: 0,
        completed: false,
        doNum: 0,
        records: [
          HabitRecords(time: 111, content: 'content1'),
          HabitRecords(time: 112, content: 'content2')
        ]);
  }

  @override
  List<Object> get props => [
        this.id,
        this.name,
        this.iconPath,
        this.mainColor,
        this.mark,
        this.remindTimes,
        this.completeDays,
        this.completeTime,
        this.period,
        this.createTime,
        this.modifyTime,
        this.completed,
        this.doNum,
        this.records,
        this.todayChek,
        this.totalCheck
      ];

  Habit copyWith(
      {String id,
      String name,
      String iconPath,
      int mainColor,
      String mark,
      List<String> remindTimes,
      List<int> completeDays,
      int completeTime,
      int period,
      int createTime,
      int modifyTime,
      bool completed,
      int doNum,
      List<HabitRecords> records,
      List<int> todayChek,
      Map<String, List<int>> totalCheck}) {
    return Habit(
      id: id ?? this.id,
      name: name ?? this.name,
      iconPath: iconPath ?? this.iconPath,
      mainColor: mainColor ?? this.mainColor,
      mark: mark ?? this.mark,
      remindTimes: remindTimes ?? this.remindTimes,
      completeDays: completeDays ?? this.completeDays,
      completeTime: completeTime ?? this.completeTime,
      period: period ?? this.period,
      createTime: createTime ?? this.createTime,
      modifyTime: modifyTime ?? this.modifyTime,
      completed: completed ?? this.completed,
      doNum: doNum ?? this.doNum,
      records: records ?? this.records,
      todayChek: todayChek ?? this.todayChek,
      totalCheck: totalCheck ?? this.totalCheck,
    );
  }
}
